### All users

GET http://localhost:8090/user
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Get user by id

GET http://localhost:8090/user/3001
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Create user

POST http://localhost:8090/user
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "login": "new_user",
  "password": "password",
  "roles": [
    "user"
  ]
}

### Update user

PUT http://localhost:8090/user
Content-Type: application/json
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

{
  "id": 3001,
  "login": "new_login",
  "password": "newpassword",
  "roles": [
    "user"
  ]
}
